### ISSUE TITLE
Provide a CLI

### ISSUE THREAD

**Issue by mxmlnkn** [mgzip/mgzip#14]
Hello,

The parallelization sounded interesting, so I wanted to test it out quickly but it seems this is only a library. I think, as it adds some new features over other parallel gzip programs, it might be a good idea to offer it as a command line tool, too (when it is installed via pip). This would only require a small function, e.g., using argparse and setting that method as a CLI entry point in setuptools.

Edit: Or is this format identical to [BGZF](http://samtools.github.io/hts-specs/SAMv1.pdf)?

**Comment by timhughes** [comment]
You can call it on the command line with `python -m pgzip`

See https://github.com/pgzip/pgzip/releases/tag/0.3.1

**Comment by mxmlnkn** [comment]
Ah nice! My bad, I only tested mgzip like this and it just seems to hang waiting for input and there was no help.
