### ISSUE TITLE
Adding typing to pgzip.py

### ISSUE THREAD

**Issue by trodery** [mgzip/mgzip#16]
I'd like to spruce up docstrings and add PEP compliant typing to `pgzip.py`. There are various levels of support for typing across Python 3. Some typing features available in more recent versions of Python are not compatible with older versions of Python. Which versions of Python 3 would you like to maintain compatibility with?

**Comment by timhughes** [comment]
I think it is generally accepted that anything >= 3.6 is still in use for a lot of systems. I don't know if any of the other maintainers have any preference.

> Some typing features available in more recent versions of Python are not compatible with older versions of Python

Do you have any specifics of which older versions are affected by which features?

**Comment by trodery** [comment]
Regarding typing, I think the only basic major change between 3.6 and 3.7 is the use of forward references. This is only supported in Python 3.7 and later via `from __future__ import annotations`. What this means is that the functions located at the top of `pgzip.py` can't return the type of the classes below that. Not adding typing to those functions doesn't remove anything existing so I think it's ok to ignore typing those functions.

For docstrings, do you have any preferred format? I use Google style docstrings for everything I do and it is supported by `sphinx` as well. Google style docstrings are, in my opinion, more readable in the code base vs. other styles.

Lastly, what are your thoughts on formatting the code using a formatter such as `black`? This would help keep formatting and styling consistent across the code base regardless of who contributes. Consistent enforcement of string formatting and breaking up longer lines is nice.

**Comment by alexitx** [comment]
I use the Pylint and Flake8 linters for most projects and I'm familiar with the Google docstrings. The 3.6 typing is used widely from what I see, but I'm not sure if or how much backwards compatible the newer system in 3.9 is. Either way I think it's nice to keep >=3.6 compatibility.

I haven't used any formatters, I generally use the style of the project, but I'm fine with anything that is easy to set up and will help with consistency.

**Comment by timhughes** [comment]
Lets keep 3.6 support for a while. The more compatibility the better in my opinion.
Google style docstrings are fine by me 
I use black for all my formatting normally so happy with that.

**Comment by trodery** [comment]
Thank you for clarification on all of those items. There are *a lot* of changes after formatting the code base using `black`. Given this, I'd like to propose the following:
* Format `pgzip.zip`, `__main__.py`, and `__init__.py` using `black`
* Verify that all tests are passing
* Submit a PR for the formatting changes that `black` has made
* Add typing and submit another PR

I have the formatting and typing changes locally and I'm running it without any issues so I'm fairly confident nothing will break. :) Let me know if the above workflow is ok or if it needs modifications.

**Comment by timhughes** [comment]
sound good to me.

**Comment by timhughes** [comment]
I have merged https://github.com/pgzip/pgzip/pull/17 thanks

**Comment by timhughes** [comment]
@trodery was there anything more you wanted to add or can I close this ticket ?
