### ISSUE TITLE
No PYPI release for version 0.3.3

### ISSUE THREAD

**Issue by RobbyRed98** [mgzip/mgzip#26]
Although pgzip version 0.3.3 has been released on Github, there is no corresponding release on PYPI.
Could it be that the Github action described in #12 was not triggered, since the `__version__` variable in tag 0.3.3 still specifies `0.3.2`: https://github.com/pgzip/pgzip/blob/6c995fda8b2f53fd916f33fa4d4e5a98a0ef2556/pgzip/pgzip.py#L28

**Comment by timhughes** [comment]
Bumped it to 0.3.4 and tagged a new release . I need to come up with a better workflow.  

https://pypi.org/project/pgzip/0.3.4/
