### ISSUE TITLE
OSError: Not a gzipped file` or `EOFError: Ran out of input` when being called simultaneously by multiple processes

### ISSUE THREAD

**Issue by tle4336** [mgzip/mgzip#34]
@timhughes Dear Mr. Hughes, I am currently using this pgzip package within a multiprocessing environment on UNIX system with `fork/forkserver` method. The clause `with pgzip.open([file directory path], 'rb', thread=8) as f: pickle.loads(blosc.decompress(f.read()))` has caused issue such as `OSError: Not a gzipped file` or `EOFError: Ran out of input`. I am wondering if you could help look into this package's capability to be run successfully in the parallel environment. Currently, I can only think of this workaround, which I am unsure if it would work:

`import fnctl`

`with pgzip.open([file_path], 'rb', thread=8) as f: `

     f_lock = fnctl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_UN) --- ## the main idea is to create an identical file to f, but it is locked to prevent other processes from accessing to this file.

     pickle.loads(blosc.decompress(f_lock.read())`

**Comment by timhughes** [comment]
The goal of this package is to have a drop in replacement for for the standard gzip module. Can you do what you want with the standard gzip module. If so can you please provide a working example so I can better understand what you are trying to achieve.

**Comment by timhughes** [comment]
Stale
