### ISSUE TITLE
Support streaming output

### ISSUE THREAD

**Issue by rizsotto** [mgzip/mgzip#35]
Hi there,

I have a use case where I need to upload a `.tar.gz` file to a server. The content of the archive are machine learning models, where the size can be big (from 50GB to 120GB). I am trying to stream the `tarfile` output to `pgzip` and the `pgzip` output to `request`. I managed to have a streaming output from `tarfile`, but the `pgzip` only emits the output when all input is read. (Therefore blocking the upload and allocating a lot of memory.) I have tested that the `request` library also support streaming input. Also tried the `zlib` library to compress the output of the `tarfile`. But because it is not parallel, it is slower.

Is it currently possible that `pgzip` can write the output immediately the compressed chunk is available? Would it be possible to implement it if this is not yet available?

In my code, I pass a file like object to the `pgzip.open()` method. And the implementation of that object is calling a `Queue.put()` when the `write()` is called. What I seen so far, that the queue put is only called after the last `write()` is called.

I am happy to work on PRs, but need some guidance.

And thanks for this awsome library!

**Comment by timhughes** [comment]
See #37
