### ISSUE TITLE
Support for bgzipped files

### ISSUE THREAD

**Issue by bkille** [mgzip/mgzip#36]
Same issue as #19, and similar to @ruochiz  my file was compressed via `bgzip` not `gzip`. Is it possible to add support for bgzipped files?

**Comment by timhughes** [comment]
I believe that pgzip and bgzip are incompatible. They both split the data into blocks when compressing in a similar way but for different reasons. pgzip does it for parallelism, bgzip does it to enable extracting just part of a compressed file. 

As for adding support, I no longer use pgzip professionally as I have changed jobs. I am happy to accept new feature changes if they have tests and don't break backwards compatibility but I don't have the time to work on this myself.
