### ISSUE TITLE
mgzip name on pypi

### ISSUE THREAD

**Issue by timhughes** [mgzip/mgzip#4]
The package name `mgzip` on pypi https://pypi.org/project/mgzip/ is owned by @vinlyx

As I see it we have the following options:

1. Manage to contact @vinlyx and have him transfer the name over to us
2. rename the package
3. rename the package on pypi but retain the same import name. eg `scikit-learn` is imported as `sklearn`
4. follow the pypi abandoned package process https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project

**Comment by timhughes** [comment]
I have asked @vinlyx to transfer the pypi name and github project over to my personal accounts on each so I can then juggle then into the correct places for an organisation. https://github.com/vinlyx/mgzip/issues/16

**Comment by alexitx** [comment]
According to the GitHub policy a transfer cannot happen without owner approval, and PyPI states:
> the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround

I've also contacted @vinlyx, but it's unlikely that we will get a response. I guess we'll just have to wait and see.

In that case we might need to use something like `mgzip2` as the package namespace which a lot of forked projects do. I'm only concerned about the org/repo name creating confusion beacuse the package/module name will differ.

Also, should we start development and accepting PRs right away or wait for the name situation to get resolved?

**Comment by jamestwebber** [comment]
> In that case we might need to use something like mgzip2 as the package namespace which a lot of forked projects do. I'm only concerned about the org/repo name creating confusion beacuse the package/module name will differ.

Another possibility is to change the name entirely, including the package name, and make a note of the change/ancestry in the README. Something like `multigzip`, maybe.

**Comment by jamestwebber** [comment]
> Also, should we start development and accepting PRs right away or wait for the name situation to get resolved?

I think that depends on how much free time you have 😁 But if you open a PR to this repo and @vinlyx shows up and wants to continue maintaining the package and repo, it's easy enough to point that PR to the old repo.

**Comment by timhughes** [comment]
> Another possibility is to change the name entirely, including the package name, and make a note of the change/ancestry in the README. Something like `multigzip`, maybe.

This feels like the fastest way forwards.

**Comment by timhughes** [comment]
Just did all the rename but stupidly didn't check pypi to make sure it was available. Any other suggestions ?

**Comment by jamestwebber** [comment]
😂  I should have checked that before suggesting the name...maybe `pgzip` for parallel and/or (multi)process? Also reminiscent of `pigz` but not stepping on that name.

Something simple like `mgzip2` is also fine, I think. I don't imagine any of us are planning to add a ton of new features to this project, just merging some bug-fixes and things. So a unique name that keeps a connection to the original repo is nice.

But I could be wrong about that! There are certainly some nice features that would be cool to add here, but I doubt I will be the one to try them.

**Comment by timhughes** [comment]
Rename is complete and we are now available on pypi at https://pypi.org/project/pgzip/


```
❯ pip install pgzip
Defaulting to user installation because normal site-packages is not writeable
Collecting pgzip
  Downloading pgzip-0.3.0-py3-none-any.whl (12 kB)
Installing collected packages: pgzip
Successfully installed pgzip-0.3.0
```
