### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jamestwebber** [mgzip/mgzip#5]
This is an open issue on the original repo, https://github.com/vinlyx/mgzip/issues/14

Creating a conda-forge package is relatively simple to do for a pure-Python package like this. The [documentation](https://conda-forge.org/docs/maintainer/adding_pkgs.html) is relatively straight-forward and they provide automation that makes it simple to maintain once everything is set up. For a package that's already on PyPI, updates are very simple.

I'm doing this for a couple other projects so would be willing to set this up, once we have sorted out the PyPI issues and incorporated any other initial changes.

**Comment by jamestwebber** [comment]
Clearly I totally failed to do this, apologies for that. Thankfully it looks like @haorenfsa took up the mantle and is maintaining [pgzip-feedstock](https://github.com/conda-forge/pgzip-feedstock), thank you!

**Comment by haorenfsa** [comment]
Oh, our project https://github.com/towhee-io/towhee uses this lib and also need to be released to conda-forge. 😄

By the way, if you're guys are willing to help maintaining the feedstock plz contact me. I'm maintaining multiple projects, so the upgrades may not be done in time.

**Comment by timhughes** [comment]
@haorenfsa I just saw this comment. What is involved in maintaining the feedstock? If it is something minor like bumping the version in a config or something then I am happy to kick that off after any new releases.

**Comment by haorenfsa** [comment]
@timhughes yes, mainly bumping the version. The conda-forge bot will launch PR automatically, maintainer just need to review the changes. I'll add you in the feedstock repo.

**Comment by haorenfsa** [comment]
@timhughes check  https://github.com/orgs/conda-forge/invitation
